const images = {
  logo: require('./logo.png'),
  banners: {
    'ad-sm': require('./banners/ad-sm.png'),
    ad: require('./banners/ad.png'),
    'banner-item1': require('./banners/banner-item1.jpg'),
    'banner-item2': require('./banners/banner-item2.jpg'),
    'banner-item3': require('./banners/banner-item3.jpg'),
    banner1: require('./banners/banner1.jpg'),
    banner2: require('./banners/banner2.jpg'),
    banner3: require('./banners/banner3.jpg'),
    banner4: require('./banners/banner4.jpg'),
    banner5: require('./banners/banner5.jpg'),
    banner6: require('./banners/banner6.jpg'),
    banner7: require('./banners/banner7.jpg'),
    banner8: require('./banners/banner8.jpg'),
    banner9: require('./banners/banner9.jpg'),
    slide1: require('./banners/slide1.jpg'),
    slide2: require('./banners/slide2.jpg'),
    slide3: require('./banners/slide3.jpg'),
  },
  icon: {
    flags: {
      AU: require('./icons/flags/AU.png'),
      'AU@2x': require('./icons/flags/AU@2x.png'),
      CN: require('./icons/flags/CN.png'),
      'CN@2x': require('./icons/flags/CN@2x.png'),
      DE: require('./icons/flags/DE.png'),
      'DE@2x': require('./icons/flags/DE@2x.png'),
      GB: require('./icons/flags/GB.png'),
      'GB@2x': require('./icons/flags/GB@2x.png'),
      IN: require('./icons/flags/IN.png'),
      'IN@2x': require('./icons/flags/IN@2x.png'),
      RU: require('./icons/flags/RU.png'),
      'RU@2x': require('./icons/flags/RU@2x.png'),
      TR: require('./icons/flags/TR.png'),
      'TR@2x': require('./icons/flags/TR@2x.png'),
      US: require('./icons/flags/US.png'),
      'US@2x': require('./icons/flags/US@2x.png'),
      UZ: require('./icons/flags/UZ.png'),
      'UZ@2x': require('./icons/flags/UZ@2x.png'),
    },
    'pay-american-ex': require('./icons/pay-american-ex.png'),
    'pay-bank': require('./icons/pay-bank.png'),
    'pay-mastercard': require('./icons/pay-mastercard.png'),
    'pay-visa-el': require('./icons/pay-visa-el.png'),
    'pay-visa': require('./icons/pay-visa.png'),
  },
  items: {
    'mot': require('./items/1.jpg'),
    'hai': require('./items/2.jpg'),
    'ba': require('./items/3.jpg'),
    'bon': require('./items/4.jpg'),
    'nam': require('./items/5.jpg'),
    'sau': require('./items/6.jpg'),
    'bay': require('./items/7.jpg'),
    'tam': require('./items/8.jpg'),
    'chin': require('./items/9.jpg'),
    'muoi': require('./items/10.jpg'),
    'muoiMot': require('./items/11.jpg'),
    'muoiHai': require('./items/12.jpg'),
    'muoiBa': require('./items/13.jpg'),
    'muoiBon': require('./items/14.jpg'),
    'muoiNam': require('./items/15.jpg'),
    'muoiNamSub1': require('./items/15-1.jpg'),
    'muoiNamSub2': require('./items/15-2.jpg'),
  },
  misc: {
    appstore: require('./misc/appstore.png'),
    payments: require('./misc/payments.png'),
    playmarket: require('./misc/playmarket.png'),
  },
  posts: {
    1: require('./posts/1.jpg'),
    2: require('./posts/2.jpg'),
    3: require('./posts/3.jpg'),
    4: require('./posts/4.jpg'),
  },
};

export default images;
