import images from '~/access/images';

export const GetAllProduct = [
  {
    id: 1,
    images: images.items.mot,
    subImages: [images.items.muoiNamSub1, images.items.muoiNamSub2, images.items.muoiNamSub1, images.items.muoiNamSub2],
    title: 'Well made women clothes with trending collection ',
    evaluate: 4,
    reviewsNumber: 132,
    ordersNumber: 154,
    price: 465,
    discription:
      'Compact sport shoe for running, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    Manufacturer: 'Great textile Ltd.',
    ArticleNumber: '596 065',
    Guarantee: '2 year',
    DeliveryTime: 3,
    Availabilty: 'in Stock',
    address: ' Guanjou, China',
    company: 'Guangzhou Yichuang Electronic Co',
  },
  {
    id: 2,
    images: images.items.hai,
    subImages: [images.items.muoiNamSub1, images.items.muoiNamSub2, images.items.muoiNamSub1, images.items.muoiNamSub2],
    title: 'Well made women clothes with trending collection ',
    Evaluate: 4,
    reviewsNumber: 132,
    ordersNumber: 154,
    price: 465,
    discription:
      'Compact sport shoe for running, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    Manufacturer: 'Great textile Ltd.',
    ArticleNumber: '596 065',
    Guarantee: '2 year',
    DeliveryTime: 3,
    Availabilty: 'in Stock',
    address: ' Guanjou, China',
    company: 'Guangzhou Yichuang Electronic Co',
  },
  {
    id: 3,
    images: images.items.ba,
    subImages: [images.items.muoiNamSub1, images.items.muoiNamSub2, images.items.muoiNamSub1, images.items.muoiNamSub2],
    title: 'Well made women clothes with trending collection ',
    Evaluate: 4,
    reviewsNumber: 132,
    ordersNumber: 154,
    price: 465,
    discription:
      'Compact sport shoe for running, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    Manufacturer: 'Great textile Ltd.',
    ArticleNumber: '596 065',
    Guarantee: '2 year',
    DeliveryTime: 3,
    Availabilty: 'in Stock',
    address: ' Guanjou, China',
    company: 'Guangzhou Yichuang Electronic Co',
  },
  {
    id: 4,
    images: images.items.bon,
    subImages: [images.items.muoiNamSub1, images.items.muoiNamSub2, images.items.muoiNamSub1, images.items.muoiNamSub2],
    title: 'Well made women clothes with trending collection ',
    Evaluate: 4,
    reviewsNumber: 132,
    ordersNumber: 154,
    price: 465,
    discription:
      'Compact sport shoe for running, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    Manufacturer: 'Great textile Ltd.',
    ArticleNumber: '596 065',
    Guarantee: '2 year',
    DeliveryTime: 3,
    Availabilty: 'in Stock',
    address: ' Guanjou, China',
    company: 'Guangzhou Yichuang Electronic Co',
  },
  {
    id: 5,
    images: images.items.nam,
    subImages: [images.items.muoiNamSub1, images.items.muoiNamSub2, images.items.muoiNamSub1, images.items.muoiNamSub2],
    title: 'Well made women clothes with trending collection ',
    Evaluate: 4,
    reviewsNumber: 132,
    ordersNumber: 154,
    price: 465,
    discription:
      'Compact sport shoe for running, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    Manufacturer: 'Great textile Ltd.',
    ArticleNumber: '596 065',
    Guarantee: '2 year',
    DeliveryTime: 3,
    Availabilty: 'in Stock',
    address: ' Guanjou, China',
    company: 'Guangzhou Yichuang Electronic Co',
  },
  {
    id: 6,
    images: images.items.sau,
    subImages: [images.items.muoiNamSub1, images.items.muoiNamSub2, images.items.muoiNamSub1, images.items.muoiNamSub2],
    title: 'Well made women clothes with trending collection ',
    Evaluate: 4,
    reviewsNumber: 132,
    ordersNumber: 154,
    price: 465,
    discription:
      'Compact sport shoe for running, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    Manufacturer: 'Great textile Ltd.',
    ArticleNumber: '596 065',
    Guarantee: '2 year',
    DeliveryTime: 3,
    Availabilty: 'in Stock',
    address: ' Guanjou, China',
    company: 'Guangzhou Yichuang Electronic Co',
  },
  {
    id: 7,
    images: images.items.muoiNam,
    subImages: [images.items.muoiNamSub1, images.items.muoiNamSub2, images.items.muoiNamSub1, images.items.muoiNamSub2],
    title: 'Well made women clothes with trending collection ',
    Evaluate: 4,
    reviewsNumber: 132,
    ordersNumber: 154,
    price: 465,
    discription:
      'Compact sport shoe for running, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    Manufacturer: 'Great textile Ltd.',
    ArticleNumber: '596 065',
    Guarantee: '2 year',
    DeliveryTime: 3,
    Availabilty: 'in Stock',
    address: ' Guanjou, China',
    company: 'Guangzhou Yichuang Electronic Co',
  },
  {
    id: 8,
    images: images.items.muoiNam,
    subImages: [images.items.muoiNamSub1, images.items.muoiNamSub2, images.items.muoiNamSub1, images.items.muoiNamSub2],
    title: 'Well made women clothes with trending collection ',
    Evaluate: 4,
    reviewsNumber: 132,
    ordersNumber: 154,
    price: 465,
    discription:
      'Compact sport shoe for running, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    Manufacturer: 'Great textile Ltd.',
    ArticleNumber: '596 065',
    Guarantee: '2 year',
    DeliveryTime: 3,
    Availabilty: 'in Stock',
    address: ' Guanjou, China',
    company: 'Guangzhou Yichuang Electronic Co',
  },
  {
    id: 9,
    images: images.items.bay,
    subImages: [images.items.muoiNamSub1, images.items.muoiNamSub2, images.items.muoiNamSub1, images.items.muoiNamSub2],
    title: 'Well made women clothes with trending collection ',
    evaluate: 4,
    reviewsNumber: 132,
    ordersNumber: 154,
    price: 465,
    discription:
      'Compact sport shoe for running, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    Manufacturer: 'Great textile Ltd.',
    ArticleNumber: '596 065',
    Guarantee: '2 year',
    DeliveryTime: 3,
    Availabilty: 'in Stock',
    address: ' Guanjou, China',
    company: 'Guangzhou Yichuang Electronic Co',
  },
  {
    id: 10,
    images: images.items.tam,
    subImages: [images.items.muoiNamSub1, images.items.muoiNamSub2, images.items.muoiNamSub1, images.items.muoiNamSub2],
    title: 'Well made women clothes with trending collection ',
    Evaluate: 4,
    reviewsNumber: 132,
    ordersNumber: 154,
    price: 465,
    discription:
      'Compact sport shoe for running, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    Manufacturer: 'Great textile Ltd.',
    ArticleNumber: '596 065',
    Guarantee: '2 year',
    DeliveryTime: 3,
    Availabilty: 'in Stock',
    address: ' Guanjou, China',
    company: 'Guangzhou Yichuang Electronic Co',
  },
  {
    id: 11,
    images: images.items.chin,
    subImages: [images.items.muoiNamSub1, images.items.muoiNamSub2, images.items.muoiNamSub1, images.items.muoiNamSub2],
    title: 'Well made women clothes with trending collection ',
    Evaluate: 4,
    reviewsNumber: 132,
    ordersNumber: 154,
    price: 465,
    discription:
      'Compact sport shoe for running, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    Manufacturer: 'Great textile Ltd.',
    ArticleNumber: '596 065',
    Guarantee: '2 year',
    DeliveryTime: 3,
    Availabilty: 'in Stock',
    address: ' Guanjou, China',
    company: 'Guangzhou Yichuang Electronic Co',
  },
  {
    id: 12,
    images: images.items.muoi,
    subImages: [images.items.muoiNamSub1, images.items.muoiNamSub2, images.items.muoiNamSub1, images.items.muoiNamSub2],
    title: 'Well made women clothes with trending collection ',
    Evaluate: 4,
    reviewsNumber: 132,
    ordersNumber: 154,
    price: 465,
    discription:
      'Compact sport shoe for running, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    Manufacturer: 'Great textile Ltd.',
    ArticleNumber: '596 065',
    Guarantee: '2 year',
    DeliveryTime: 3,
    Availabilty: 'in Stock',
    address: ' Guanjou, China',
    company: 'Guangzhou Yichuang Electronic Co',
  },
  {
    id: 13,
    images: images.items.muoiMot,
    subImages: [images.items.muoiNamSub1, images.items.muoiNamSub2, images.items.muoiNamSub1, images.items.muoiNamSub2],
    title: 'Well made women clothes with trending collection ',
    Evaluate: 4,
    reviewsNumber: 132,
    ordersNumber: 154,
    price: 465,
    discription:
      'Compact sport shoe for running, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    Manufacturer: 'Great textile Ltd.',
    ArticleNumber: '596 065',
    Guarantee: '2 year',
    DeliveryTime: 3,
    Availabilty: 'in Stock',
    address: ' Guanjou, China',
    company: 'Guangzhou Yichuang Electronic Co',
  },
  {
    id: 14,
    images: images.items.muoiHai,
    subImages: [images.items.muoiNamSub1, images.items.muoiNamSub2, images.items.muoiNamSub1, images.items.muoiNamSub2],
    title: 'Well made women clothes with trending collection ',
    Evaluate: 4,
    reviewsNumber: 132,
    ordersNumber: 154,
    price: 465,
    discription:
      'Compact sport shoe for running, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    Manufacturer: 'Great textile Ltd.',
    ArticleNumber: '596 065',
    Guarantee: '2 year',
    DeliveryTime: 3,
    Availabilty: 'in Stock',
    address: ' Guanjou, China',
    company: 'Guangzhou Yichuang Electronic Co',
  },
  {
    id: 15,
    images: images.items.muoiBa,
    subImages: [images.items.muoiNamSub1, images.items.muoiNamSub2, images.items.muoiNamSub1, images.items.muoiNamSub2],
    title: 'Well made women clothes with trending collection ',
    Evaluate: 4,
    reviewsNumber: 132,
    ordersNumber: 154,
    price: 465,
    discription:
      'Compact sport shoe for running, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    Manufacturer: 'Great textile Ltd.',
    ArticleNumber: '596 065',
    Guarantee: '2 year',
    DeliveryTime: 3,
    Availabilty: 'in Stock',
    address: ' Guanjou, China',
    company: 'Guangzhou Yichuang Electronic Co',
  },
  {
    id: 16,
    images: images.items.muoiBon,
    subImages: [images.items.muoiNamSub1, images.items.muoiNamSub2, images.items.muoiNamSub1, images.items.muoiNamSub2],
    title: 'Well made women clothes with trending collection ',
    Evaluate: 4,
    reviewsNumber: 132,
    ordersNumber: 154,
    price: 465,
    discription:
      'Compact sport shoe for running, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    Manufacturer: 'Great textile Ltd.',
    ArticleNumber: '596 065',
    Guarantee: '2 year',
    DeliveryTime: 3,
    Availabilty: 'in Stock',
    address: ' Guanjou, China',
    company: 'Guangzhou Yichuang Electronic Co',
  },
];
